name: Java CI with Maven
on:
  push:
    branches: [ main ]
  pull_request:
    branches: '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
      - name: Set up Node 18
        uses: actions/setup-node@v1
        with:
          node-version: '18'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 8
          cache: maven
      - name: Build with Maven
        run: mvn -ntp -U clean verify
        env:
          AWS_REGION: us-west-2
      - name: Upload Failed Test Report
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Failed Test Report
          path: target/surefire-reports
